export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST';
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS';
export const TRANSACTION_FAILURE = 'TRANSACTION_FAILURE';
export const SET_FORM_FIELD = 'SET_FORM_FIELD';
export const RESET_FORM = 'RESET_FORM';
export const HIDE_PROGRESS_MESSAGE = 'HIDE_PROGRESS_MESSAGE';